#-------------------------------
# General Site Settings

menu:
- {name: 'Neural Style Transfer', url: ''}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'CS534 Project'
  rel-author: 'N/A'
  rel-publisher: 'N/A'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

#-------------------------------
# Work Section

projects:
- {name: 'Summary', folder: 'NST', file: 'projects/NST.html'}
- {name: 'Project Proposal', folder: 'Proposal', file: 'projects/Proposal.html'}
- {name: 'Midterm Report', folder: 'Report', file: 'projects/Report.html'}
- {name: 'Slides', folder: 'Slides', file: 'projects/Slides.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://www.github.com/swrj'}
- {icon: 'envelope', link: 'mailto:srao24@wisc.edu'}
- {icon: 'github', link: 'https://www.github.com/rohitbs19'}
- {icon: 'envelope', link: 'mailto:battula2@wisc.edu'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
